// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mOwWUR3Vq9JnnFD-lQyFxH156F8OSyI',
    appId: '1:205437649078:web:3779ba1a74cd9ef8c96617',
    messagingSenderId: '205437649078',
    projectId: 'medicalapp-6d39b',
    authDomain: 'medicalapp-6d39b.firebaseapp.com',
    storageBucket: 'medicalapp-6d39b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqaNtiQ6IIOwZA0EA8ySr_YKKQEC7Y_s',
    appId: '1:205437649078:android:46c944aac773f384c96617',
    messagingSenderId: '205437649078',
    projectId: 'medicalapp-6d39b',
    storageBucket: 'medicalapp-6d39b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBuAoN49TB0VytQzfeeJxmAWOODU-Evo',
    appId: '1:205437649078:ios:03e2a20bc917f3edc96617',
    messagingSenderId: '205437649078',
    projectId: 'medicalapp-6d39b',
    storageBucket: 'medicalapp-6d39b.appspot.com',
    iosClientId: '205437649078-a6sp0dqphiqjg96uutve378vclcln5jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBuAoN49TB0VytQzfeeJxmAWOODU-Evo',
    appId: '1:205437649078:ios:d61d248c05a48a50c96617',
    messagingSenderId: '205437649078',
    projectId: 'medicalapp-6d39b',
    storageBucket: 'medicalapp-6d39b.appspot.com',
    iosClientId: '205437649078-vt2ibojvr57srgj7qn06hi86gsng3asn.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp.RunnerTests',
  );
}
